---
minimum_pre_commit_version: 3.3.3

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.31.0
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
## YAML Lint
# We have to adjust this hook, which looks for yaml files,
# because some of our files are 'disguised' and not found by
# 'identify', used by pre-commit. So we basically say...
# All files that end '.yaml' or '.yaml.j2'
# See https://pre-commit.com/#filtering-files-with-types
- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
  - id: yamllint
    types:
    - file
    files: (\.yaml|\.yaml.j2)$
