---

# Operator state?
# One of 'present' or 'absent'
jo_state: present

# The kubernetes config file.
jo_kubeconfig: SetMe

# The Operator container image and tag
jo_image: informaticsmatters/data-manager-job-operator
jo_image_tag: SetMe

# The namespace of the Job Operator.
jo_namespace: data-manager-job-operator

# Job pod node selection.
# Jobs will be run on nodes that have labels keys and values defined here...
jo_pod_node_selector_key: informaticsmatters.com/purpose-worker
jo_pod_node_selector_value: 'yes'

# Nextflow executor queue size?
jo_nf_executor_queue_size: 100
# Use ANSI log?
# Operator default is 'no'.
jo_nf_ansi_log: no

# A priority class for the operator Pod
jo_priority_class: ''
# Apply Priority Class to Pods launched
jo_apply_pod_priority_class: no

# Default Job CPU and memory settings
jo_pod_default_cpu: '1'
jo_pod_default_memory: '1Gi'

# The pre-delete delay (seconds) for Pods.
# After a Pod's finished it's deleted after this period has elapsed.
jo_pre_delete_delay_s: 5
